# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PqcgwZTH2_LbhtADCQvoeEGkjzpw8KSU
"""

i = 1
while i <= 10:
  print(i)
  i+=1

i = 1
while i <= 100:
  if i % 2 == 0:
    print(i)
  i+=1

i = 1
sum = 0
while i <= 100:
  sum += i
  i+= 1
print(sum)

sum = 0
while True:
  num = (int(input("숫자를 입력하세요:")))
  if(num == 0):
    break
  sum += num
print(sum)

maxvalue = 0
while True:
  num = int(input("숫자를 입력하세요:"))
  if num == 0:
    break
  if num > maxvalue:
    maxvalue = num
print(maxvalue)

num = int(input("10진수를 입력하세요 : "))
binary =""
while num > 0:
  remainder = num % 2
  binary = str(remainder) + binary
  num = num // 2
print("입력한 수의 2진수 표현: ",binary)

fruits = ["apple","banana","cherry"]
for fruit in fruits:
  print(fruit,end="")

numbers = [1,2,3,4,5]
sum = 0
for num in numbers:
  sum += num
print(sum)

colors = ("red", "green", "blue")
for color in colors:
  print(color)

text = "Python"
for char in text:
  print(char)

for i in range(1,11):
  print(i)

for i in range(1,11):
  print(i)

for i in range(2,11,2):
  print(i)

for i in range(10,0,-1):
  print(i)

for i in range(2,10):
  for j in range(1,10):
    print(f"{i}*{j}={i*j}")

for i in range(1,6):
  for j in range(1, i+1):
    print("*",end="")
  print()

for i in range(4,0,-1):
  for j in range(1,i+1):
    print("*",end="")
  print()

n = int(input("숫자를 입력하세요: "))
sum = 0
for i in range(1,n+1):
    if(i % 3 == 0 or i % 5 == 0):
      sum += i
print(sum)

min = 100
max = 0
for i in range(5):
  num = int(input(f"{i+1}번째 숫자를 입력하세요:"))
  if num < min:
    min = num
  if num > max:
    max = num
print(min , max)

sum = 0
while sum < 100:
  num = int(input("숫자를 입력하세요 : "))
  sum += num
print(sum)

n = int(input("몇번째 항을 출력할까요? : "))
if n < 3:
  result = 1
else:
  i = 3
  a = 1
  b = 1
  while i <= n:
    result = a + b
    a = b
    b = result
    i += 1
print(f"피보나치 수열의 {n}번째 항은 ",result,"입니다")

while True:
  x = int(input("숫자를 입력하세요 : "))
  if x == 0:
    break
  elif x < 0:
    print("잘못된 입력입니다.")
    pass
  else:
    print("입력한 숫자는{} 입니다.".format(x))

for i in range(1,10):
  if i == 5:
    pass
  else:  
    print(i)

vowels = ['a','e','i','o','u']
input_str = input("Enter a string: ")

output_str = ""
for char in input_str:
  if char in vowels:
    pass
  else:
    output_str += char
print("Modified string:",output_str)

import random
sn = random.randint(1,100)
while True:
  guess = int(input("랜덤 숫자를 맞춰보세요(1~100) : "))
  if guess > sn:
    print("Down")
  elif guess < sn:
    print("Up")
  else:
    print("Correct!!")
    break

import random
fruits = ['apple','banana','orange','pear']
random.shuffle(fruits)
print(fruits)

import random
num1, num2 = random.randint(1,6), random.randint(1,6)
if num1 + num2 == 7:
  print("Win!!")
else:
  print("Lose")

while True:
  a = input("숫자 a를 입력하세요 : ")
  if a == 'exit':
    break
  a = int(a)
  b = int(input("숫자 b를 입력하세요 : "))
  op = input("연산자를 입력하세요 : ")
  if op == '+':
    print(a+b)
  elif op == '-':
    print(a-b)
  elif op == '*':
    print(a*b)
  elif op == '/':
    if b == 0:
      print("0으로 나눌 수 없습니다")
    else:
      print(int(a/b))

import random
sn = random.randint(1,100)
i = 1
while i <= 5:
  guess = int(input("랜덤 숫자를 맞춰보세요(1~100) : "))
  if guess > sn:
    print("Down")
  elif guess < sn:
    print("Up")
  else:
    print("Correct!!")
    break
  if i == 5:
    print("5회 까지 맞추지 못했습니다!")
    print(f"랜덤숫자는 {sn} 입니다.")
    break
  else:
    i+=1

from random import randint
money = 50
while 0 < money < 100:
  guess = int(input("Guess : "))
  coin = randint(1,2)
  if guess == coin:
    money += 9
    print("현재 내돈은 : ", money)
  else:
    money -= 10
    print("현재 내돈은 : ", money)
  if money >= 100:
    print("승리하였습니다")
  elif money <= 0:
    print("인생퇴갤하였습니다")

a = int(input("첫번째 숫자를 입력하세요 : "))
b = int(input("두번째 숫자를 입력하세요 : "))
if a > b:
  bn = a
  ln = b
else:
  bn = b
  ln = a
while True:
  rs = bn % ln
  bn = ln
  ln = rs
  if ln <= 0:
    break
print("최대공약수는 : ", bn)

m = int(input("정수를 입력하세요"))
output = []
for n in range(1,m+1):
  if m % n == 0:
    output.append(str(n))
print(f"{m}의 약수는 {', '.join(output)} 입니다.")

S = input("문자열을 입력하세요 : ")
print(len(S))
print(S*10)
print(S.string[0:2])

