# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wwZgNptWPC7ndmfeyWTy3Yp6B5nifBPk
"""

num = int(input("숫자를 입력하세요: "))
if num % 2 == 0:
  print(f"{num}은 짝수입니다.")
else:
  print(f"{num}은 홀수입니다.")

num = int(input("숫자를 입력하세요: "))
if num > 0:
  print("양수입니다")
elif num < 0:
  print("음수입니다.")
else:
  print("0입니다.")

score = int(input("성적을 입력하세요: "))
if score >= 90:
  grade = "A"
elif score >= 80:
  grade = "B"
elif score >= 70:
  grade = "C"
elif score >= 60:
  grade = "D"
else:
  grade = "F"
print(f"당신의 학점은 {grade}입니다.")

num = 15
result = "10보다 큽니다" if num > 10 else "10보다 작거나 같습니다"
print(result)

string = input("문자열을 입력하세요.")
length = len(string) if string else 0
print("문자열의 길이는", length, "입니다.")

a = 10
b = 20
result = a if a > b else b
print(result)

a = 10
b = 20
c = 5
res = a if a < b and a < c else ( b if b < c else c)
print(res)

import math
num = float(input("양수를 입력하세요: "))
result = math.sqrt(num) if num > 0 else "잘못된 입력입니다."
print(result)

kor = int(input("국어점수 :"))
eng = int(input("영어점수 :"))
math = int(input("수학점수 :"))
avg = float((kor*0.4)+(eng*0.4)+(math*0.2))
grade = "A" if avg >= 90 else ("B" if avg >= 80 else ("C" if avg >= 70 else("D" if avg >= 60 else "F")))
print("{:.2f}".format(avg))
print(grade)

cen = float(input("cm을 입력하세요 : "))
if cen < 0:
  print("잘못된 입력입니다")
else:
  inc = cen / 2.54
  print("인치는 : ", inc , "입니다.")

a = int(input("이수한 학점을 입력하세요 : "))
if a < 40:
  print("1학년입니다")
elif 40 <= a < 80:
  print("2학년입니다")
else:
  print("졸업반입니다.")

now = int(input("현재시간을 입력하세요: "))
ampm = int(input("am이면 1, pm 이면 2를 입력하세요: "))
now = now if ampm == 1 or now == 12 else now+12
lh = int(input("경과 시간은? :"))
curh = now + lh
curh %= 24
if(curh == 0):
  print(12, "am")
elif(curh < 12):
  print(curh, "am")
elif(curh == 12):
  print(12, "pm")
else:
  print(curh-12,"pm")